name: Update Feature Prioritization

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the main branch

jobs:
  update-prioritization:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Clones your repo to the GitHub runner

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'  # Use the latest stable Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Installs Pandas and other dependencies

      - name: Run Prioritization Script
        run: python prioritization.py  # Executes your RICE score calculation script

      - name: Commit updated CSV
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add feature_prioritization.csv
          git diff --cached --quiet || git commit -m "Updated feature prioritization"
          git push
